# ref: https://docs.travis-ci.com/user/languages/python
env:
  - CODECOV_TOKEN="ad8a36f9-c676-4a72-ba13-5fc1116e4254"
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install codecov"
# command to run tests
script: 
  - tox
# after successful buid
after_success:
  - codecov --file coverage/lcov.info --disable search